In [96]:
import pandas as pd
import numpy as np
import string

data={'From_To': ['LoNDon_paris', 'MAdrid_miLAN',
'londON_StockhOlm','Budapest_PaRis', 'Brussels_londOn'],
                   
'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
                   
'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   
'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
'12. Air France', '"Swiss Air"']}
df = pd.DataFrame(data)
print("_"*35,"Input","_"*35)
print(df.dtypes)
print(df)
print("_"*35,"1","_"*35)
df['FlightNumber'] = df['FlightNumber'].astype('Int64')
for i in df.index:
    if(pd.isna((df.loc[i,'FlightNumber']))):
        df.loc[i,'FlightNumber']=df.loc[i-1,'FlightNumber']+10
print(df)  
print(df.dtypes)
print("_"*35,"2","_"*35)
temp_df=pd.DataFrame(list(df['From_To'].str.split("_")),columns=['A','B'])
print(temp_df)
print("_"*35,"3","_"*35)
for j in temp_df.columns:
    for i in temp_df.index:
        temp_df.loc[i,j]=temp_df.loc[i,j].capitalize()
print(temp_df)
print("_"*35,"4","_"*35)
df[['Country','City']]=temp_df[['A','B']]
df=df.drop('From_To',axis=1)
df=df[['Country','City','FlightNumber','RecentDelays','Airline']]
print(df)

print("_"*35,"5","_"*35)

max_len_item=0
for i in df.index:
    if(max_len_item<len(df.loc[i,'RecentDelays'])):
        max_len_item=len(df.loc[i,'RecentDelays'])   
        
ind=list(string.ascii_uppercase[:max_len_item])

for i in ind:
    df[i]=np.nan

for i in df.index:
    k=0
    for j in range(0,len(df.loc[i,'RecentDelays'])) :
        a=df.loc[i,'RecentDelays']
        df.loc[i,ind[k]]=a[j]
        k=k+1      
print(df)
print("_"*35,"6","_"*35)
df[['RecentDelays','Delay_1','Delay_2']]=df[['A','B','C']]

df=df.drop(['A','B','C'],inplace=False,axis=1)
print(df[['Country','City','FlightNumber','RecentDelays','Delay_1','Delay_2','Airline']])

___________________________________ Input ___________________________________
From_To          object
FlightNumber    float64
RecentDelays     object
Airline          object
dtype: object
            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"
___________________________________ 1 ___________________________________
            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris         10045      [23, 47]               KLM(!)
1      MAdrid_miLAN         10055            []    <Air France> (12)
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis         10075          [13]       12. Air France
4   Brussels_londOn         10085      [67, 32]          "Swiss Air"
From_To         object
FlightNumber     Int64
RecentDelays    object
Airline         object
dtype: object
___________________________________ 2 ___________________________________
          A          B
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn
___________________________________ 3 ___________________________________
          A          B
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London
___________________________________ 4 ___________________________________
    Country       City  FlightNumber  RecentDelays              Airline
0    London      Paris         10045      [23, 47]               KLM(!)
1    Madrid      Milan         10055            []    <Air France> (12)
2    London  Stockholm         10065  [24, 43, 87]  (British Airways. )
3  Budapest      Paris         10075          [13]       12. Air France
4  Brussels     London         10085      [67, 32]          "Swiss Air"
___________________________________ 5 ___________________________________
    Country       City  FlightNumber  RecentDelays              Airline     A  \
0    London      Paris         10045      [23, 47]               KLM(!)  23.0
1    Madrid      Milan         10055            []    <Air France> (12)   NaN
2    London  Stockholm         10065  [24, 43, 87]  (British Airways. )  24.0
3  Budapest      Paris         10075          [13]       12. Air France  13.0
4  Brussels     London         10085      [67, 32]          "Swiss Air"  67.0

      B     C
0  47.0   NaN
1   NaN   NaN
2  43.0  87.0
3   NaN   NaN
4  32.0   NaN
___________________________________ 6 ___________________________________
    Country       City  FlightNumber  RecentDelays  Delay_1  Delay_2  \
0    London      Paris         10045          23.0     47.0      NaN
1    Madrid      Milan         10055           NaN      NaN      NaN
2    London  Stockholm         10065          24.0     43.0     87.0
3  Budapest      Paris         10075          13.0      NaN      NaN
4  Brussels     London         10085          67.0     32.0      NaN

               Airline
0               KLM(!)
1    <Air France> (12)
2  (British Airways. )
3       12. Air France
4          "Swiss Air"